<a href="https://colab.research.google.com/github/Nikhilkumar77817/DataAnlytics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

NumPy is a Python library used for working with numbers and data in the form of arrays (like tables or lists of numbers).


* It helps you do mathematical calculations very fast.
*   It provides a special object called ndarray (N-dimensional array), which is like a super-powerful list for handling big sets of numbers.
*   It is mainly used in data science, machine learning, image processing, and scientific computing.





In [52]:
#import numpy
import numpy as np

**Creating Arrays in NumPy**

In [53]:

arr1=[1,2,3,4,5]
print(arr1)
type(arr1)

[1, 2, 3, 4, 5]


list

In [54]:
arr2 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [55]:
arr2 *  arr2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [56]:

arr2 + arr2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [57]:
arr3 = np.array([[2,5,4],[6,2,8]])
arr3

array([[2, 5, 4],
       [6, 2, 8]])

In [58]:
arr3 > arr2

array([[ True,  True,  True],
       [ True, False,  True]])

In [59]:


b=np.array([(1,2,3,4),(5,6,7,8),(2,5,8,7)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]
 [2 5 8 7]]


(3, 4)

In [60]:
# crate a numpy array of zeroes and ones
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [61]:
# crate a numpy array of zeroes and ones
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:

x=np.full((5,4),5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [63]:
# this is identity matrix
y=np.eye(5)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [64]:
y=np.arange(1,10,2)  # start=1, stop=10, step=2
print(y)

[1 3 5 7 9]


**Array Attributes**



In [65]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)   # (2,3) → 2 rows, 3 columns
print(arr.ndim)    # 2 → number of dimensions
print(arr.size)    # 6 → total elements
print(arr.dtype)   # int64 → data type


(2, 3)
2
6
int64


**create random matrix**

In [66]:
y=np.random.random((5,5))
print(y)

[[0.3991202  0.12706133 0.05528336 0.46147324 0.79472068]
 [0.16212508 0.59558686 0.5673025  0.76986594 0.21188442]
 [0.3782164  0.31071263 0.2634299  0.31274058 0.6936899 ]
 [0.73484923 0.56960261 0.8289296  0.79131996 0.33099226]
 [0.00450518 0.00719557 0.04793099 0.63546556 0.10917869]]


In [67]:
 # random integr values array within a specific range
y=np.random.randint(10,100,(3,5))
print(y)

[[96 20 79 56 58]
 [11 82 29 48 17]
 [17 30 43 19 93]]


In [68]:
arr = np.random.randn(2,3)
arr

array([[-1.19693011,  1.25013418,  0.85741916],
       [-1.23327538, -0.63387119, -0.73805997]])

In [69]:
arr * 10

array([[-11.9693011 ,  12.50134181,   8.57419164],
       [-12.33275379,  -6.3387119 ,  -7.38059974]])

In [70]:
arr + arr

array([[-2.39386022,  2.50026836,  1.71483833],
       [-2.46655076, -1.26774238, -1.47611995]])

**Indexing and Slicing**

In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [72]:
names[names != 'Bob']

array(['Joe', 'Will', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [73]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
arr = np.array([10, 20, 30, 40, 50])
#Syntax: arr[start:stop:step]

print(arr[0])     # 10
print(arr[-1])    # 50
print(arr[1:4])   # Elements from index 1 to 3 → [20 30 40]
print(arr[:3])    # First 3 elements → [10 20 30]
print(arr[2:])    # From index 2 to end → [30 40 50]
print(arr[::2])   # Every 2nd element → [10 30 50]


10
50
[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


In [75]:
# Format: arr[row, col]
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2[0, 2])   # element at 1st row, 3rd col → 3
print(arr2[:, 1])   # entire 2nd column → [2 5 8]
print(arr2[1, :])   # entire 2nd row → [4 5 6]
print(arr3[0, 0])   # Element at row 0, col 0 → 1
print(arr3[1, 2])   # Row 1, col 2 → 6
print(arr3[-1, -1]) # Last row, last col → 9



3
[2 5 8]
[4 5 6]
2
8
8


**Mathematical and Statical Operation**

In [76]:
arr3=np.random.randint(10,100,(3,5))
print(arr3)

print(np.sum(arr3))    # 15
print(np.mean(arr3))   # 3.0
print(np.median(arr3)) # 3.0
print(np.std(arr3))    # 1.414
print(np.max(arr3))    # 5
print(np.min(arr3))    # 1




[[55 91 26 26 31]
 [32 22 10 15 59]
 [29 94 44 61 73]]
668
44.53333333333333
32.0
25.6225595043812
94
10


In [77]:
arr = np.array([10, 20, 30, 40, 50])

print(np.sum(arr))      # 150 (sum)
print(np.mean(arr))     # 30.0 (average)
print(np.median(arr))   # 30.0 (middle value)
print(np.std(arr))      # 14.14 (standard deviation)
print(np.var(arr))      # 200.0 (variance)
print(np.max(arr))      # 50 (largest value)
print(np.min(arr))      # 10 (smallest value)
print(np.ptp(arr))      # 40 (max - min = peak to peak)


150
30.0
30.0
14.142135623730951
200.0
50
10
40


In [78]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("Sum of all elements:", np.sum(arr2))
print("Column-wise Sum:", np.sum(arr2, axis=0)) # column wise
print("Row-wise Sum:", np.sum(arr2, axis=1))    # row wise


Sum of all elements: 45
Column-wise Sum: [12 15 18]
Row-wise Sum: [ 6 15 24]


**Reshaping and resizing array**

In [79]:
#Transposing - Special form of reshaping
arr5 = np.arange(15).reshape((3,5))
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
arr5.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [81]:
arr6 = np.arange(16).reshape((2,2,4))
arr6

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [82]:
arr6.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [83]:
arr7 = np.array([[1, 2, 3],[4, 5, 6]])
flat = arr7.reshape(-1)   # flatten
print(flat)  # [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [84]:
# resize the array
arr8 = np.array([1, 2, 3, 4])
arr8.resize((3, 3))
print(arr8)


[[1 2 3]
 [4 0 0]
 [0 0 0]]


**Sorting**

In [85]:
Arr9 = np.array([5, 2, 9, 1, 7])
print("Sorted:", np.sort(Arr9))   # Ascending order

Sorted: [1 2 5 7 9]


In [86]:
Ar9 = np.array([[3, 7, 1],[9, 2, 6]])

print("Row-wise Sort:", np.sort(Ar9, axis=1))
print("Column-wise Sort:", np.sort(Ar9, axis=0))


Row-wise Sort: [[1 3 7]
 [2 6 9]]
Column-wise Sort: [[3 2 1]
 [9 7 6]]


In [87]:
arr9 = np.random.rand(10)
arr9

array([0.48114954, 0.28189134, 0.74207971, 0.42298959, 0.95872366,
       0.18017996, 0.68366524, 0.27256922, 0.10963121, 0.99939402])

In [88]:
arr9.sort()
arr9

array([0.10963121, 0.18017996, 0.27256922, 0.28189134, 0.42298959,
       0.48114954, 0.68366524, 0.74207971, 0.95872366, 0.99939402])

**Logical operation**

In [89]:
array1=np.array([1,2,3,4,5])
array1[array1>3]


array([4, 5])

In [90]:
array1[array1<3]


array([1, 2])

In [91]:
array1[(array1>2) & (array1<5)]

array([3, 4])

In [92]:
a = np.array([1, 0, 3, 0])
b = np.array([1, 1, 0, 0])

print("a:", a)
print("b:", b)

print("\nLogical AND:", np.logical_and(a, b))
print("Logical OR:", np.logical_or(a, b))
print("Logical NOT of a:", np.logical_not(a))
print("Logical XOR:", np.logical_xor(a, b))


a: [1 0 3 0]
b: [1 1 0 0]

Logical AND: [ True False False False]
Logical OR: [ True  True  True False]
Logical NOT of a: [False  True False  True]
Logical XOR: [False  True  True False]


In [93]:
Arr = np.arange(1, 11)

# Get only even numbers
even = Arr[Arr % 2 == 0]
print("Even numbers:", even)

# Get numbers greater than 5 and even
cond = np.logical_and(Arr > 5, Arr % 2 == 0)
print("Even > 5:", Arr[cond])


Even numbers: [ 2  4  6  8 10]
Even > 5: [ 6  8 10]


In [94]:
# np.where(condition, value_if_true, value_if_false)

ar1 = np.array([5, 15, 10, 20])
result = np.where(ar1 > 10, "High", "Low")
print(result)


['Low' 'High' 'Low' 'High']


In [95]:
# np.any() → if one is true  → return True
#np.all() → if all true  → return True

ar2 = np.array([1, 2, 3, 4, 5])
print("Any > 4:", np.any(ar2 > 4))   # True
print("All > 0:", np.all(ar2 > 0))   # True
print("All > 2:", np.all(ar2 > 2))   # False


Any > 4: True
All > 0: True
All > 2: False


**Broadcasting**

In [96]:
ar3 = np.array([1, 2, 3, 4])
print(ar3 + 5)   # scalar 5 broadcast hoga
print(ar3 * 2)   # scalar 2 broadcast hoga


[6 7 8 9]
[2 4 6 8]


In [97]:
ar4 = np.array([[1, 2, 3],[4, 5, 6]])
row = np.array([10, 20, 30])
result = ar4 + row
print(result)


[[11 22 33]
 [14 25 36]]


In [98]:
A = np.array([[1], [2], [3]])   # Shape (3,1)
B = np.array([10, 20, 30])      # Shape (3,)
print(A + B)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


**copy and view**

In [99]:
# copy= create new array
ARR = np.array([10, 20, 30, 40])
copy_arr = ARR.copy()   # deep copy

copy_arr[0] = 999
print("Copy:    ", copy_arr)


Copy:     [999  20  30  40]


In [100]:
#view = same as original
ARR1 = np.array([10, 20, 30, 40])
view_arr = ARR1.view()   # shallow copy
view_arr[0] = 999
print("View:    ", view_arr)


View:     [999  20  30  40]
